### PR TITLE
fix(#152): Added support for title translation methods

### PR DESCRIPTION
**Pull request by seandelaney**
- Added support for title translation methods.
- Prefixed `EventQuery` class methods `count`, `one` and `all` with underscores to prevent these interferring with the `ElementQuery` class.

### CODE REVIEW

**Review by gustavs-gutmanis — APPROVED** [review]
Nice, but why the renaming of `all` and the other fetcher methods?

**Comment by seandelaney** [comment]
@gustavs-gutmanis 

> Nice, but why the renaming of `all` and the other fetcher methods?

That's a good question. We were overriding the Craft core functions such as `all`, `one`, `count` etc.

In this particular PR, we needed to use the Craft's core `all` function, for example without our events cache getting in the way (if I can remember correctly). The events cache was basically inferring with the query / what I needed to do in order to achieve the translatable functionality at the time of working on this. So for my own understanding and to be clear on whats what, I guess I wanted to make sure that all of "our" versions of those functions, `all`, `one`, `count` etc were separated.

If there is a cleaner/better approach then lets get this PR updated.

**Comment by seandelaney** [comment]
@kjmartens Whats your thoughts on this - have you tested it?

**Comment by kjmartens** [comment]
@seandelaney I'll finally be testing it shortly. 😅

**Comment by seandelaney** [comment]
Adding to Craft 4 only.

**Pull request closed without merging**
