### PR TITLE
feat(SFT-957): Calendar 5 for Craft 5

### PR DESCRIPTION
**Pull request by seandelaney**

### CODE REVIEW

**Review by gustavs-gutmanis — APPROVED** [review]
Tight

**Review by kjmartens — CHANGES_REQUESTED** [review]
I did a fresh install and all looks well so far. However, I did notice an issue relating to Carbon...

When I view an event that has repeat rules (every week, 10 times) on the front end in demo templates detail page (`site.dev/calendar-demo/event/9/2024/03/12`), I get this error:

```
TypeError: Cannot assign string to property Solspace\Calendar\Library\Configurations\Occurrences::$rangeStart of type ?Carbon\Carbon in /var/www/html/vendor/solspace/craft-calendar/packages/plugin/src/Library/Configurations/CalendarConfiguration.php:32
Stack trace:
#0 /var/www/html/vendor/solspace/craft-calendar/packages/plugin/src/Elements/Event.php(1078): Solspace\Calendar\Library\Configurations\CalendarConfiguration->__construct(Array)
#1 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): Solspace\Calendar\Elements\Event->getOccurrences(Array)
#2 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(Solspace\Calendar\Elements\Event), 'occurrences', Array, 'method', false, false)
#3 /var/www/html/storage/runtime/compiled_templates/0c/0ce560760aae6130660e47f971d6087c.php(305): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(Solspace\Calendar\Elements\Event), 'occurrences', Array, 'method')
#4 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_826810868907b16c7b0afeaad521f9e6->block_content(Array, Array)
#5 /var/www/html/storage/runtime/compiled_templates/4e/4e467e9acf684019f544f56645cb2243.php(196): Twig\Template->displayBlock('content', Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_77bf0bbf45d35d1b3dc59765d55bd1b7->doDisplay(Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#8 /var/www/html/storage/runtime/compiled_templates/0c/0ce560760aae6130660e47f971d6087c.php(49): Twig\Template->display(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_826810868907b16c7b0afeaad521f9e6->doDisplay(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#12 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#13 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('/calendar-demo/...', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('/calendar-demo/...', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('/calendar-demo/...', Array, 'site')
#17 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#18 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#19 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#20 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#21 /var/www/html/web/index.php(12): yii\base\Application->run()
#22 {main}
```

---

When I attempt to migrate Calendar 4 to Calendar 5 on Craft 4 (not Craft 5), I get this error:

```
php craft migrate/all
Exception 'TypeError' with message 'Cannot assign array to property Solspace\Calendar\Models\SettingsModel::$guestAccess of type ?bool'

in /site/path/vendor/yiisoft/yii2/base/Model.php:742

Stack trace:
#0 /site/path/vendor/craftcms/cms/src/base/Model.php(220): yii\base\Model->setAttributes(Array, false)
#1 /site/path/vendor/craftcms/cms/src/base/Plugin.php(193): craft\base\Model->setAttributes(Array, false)
#2 /site/path/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#3 /site/path/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('settings', Array)
#4 /site/path/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(Solspace\Calendar\Calendar), Array)
#5 /site/path/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#6 /site/path/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct('calendar', Object(craft\console\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('calendar', Object(craft\console\Application), Array)
#8 /site/path/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#9 /site/path/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('Solspace\\Calend...', Array, Array)
#10 /site/path/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('Solspace\\Calend...', Array, Array)
#11 /site/path/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject(Array, Array)
#12 /site/path/vendor/craftcms/cms/src/services/Plugins.php(943): Craft::createObject(Array, Array)
#13 /site/path/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('calendar', Array)
#14 /site/path/vendor/craftcms/cms/src/base/ApplicationTrait.php(1649): craft\services\Plugins->loadPlugins()
#15 /site/path/vendor/craftcms/cms/src/console/Application.php(53): craft\console\Application->_postInit()
#16 /site/path/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#17 /site/path/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#18 /site/path/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#19 [internal function]: yii\console\Application->__construct(Array)
#20 /site/path/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#21 /site/path/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#22 /site/path/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#23 /site/path/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject(Array, Array)
#24 /site/path/vendor/craftcms/cms/bootstrap/bootstrap.php(250): Craft::createObject(Array)
#25 /site/path/vendor/craftcms/cms/bootstrap/console.php(42): require('/Users/kmartens...')
#26 /site/path/craft(21): require('/Users/kmartens...')
#27 {main}
```

**Comment by seandelaney** [comment]
@kjmartens PR updated

**Review by kjmartens — APPROVED** [review]
👌

**Pull request merged**
